"""Deterministic bundled-047 M0 cylinder links to BLUECAD."""

from __future__ import annotations

import hashlib
import json
import math
import shutil
import sqlite3
from decimal import Decimal, InvalidOperation
from pathlib import Path
from typing import Any
from uuid import uuid4

from pydantic import BaseModel, ConfigDict, Field, model_validator

from app.core.cad_link_schema import CAD_LINK_SCHEMA_INDEX_STATEMENTS, CAD_LINK_SCHEMA_STATEMENTS
from app.core.database import open_sqlite_connection
from app.modules.bluecad.evidence import record_validation_evidence
from app.modules.bluecad.ledger import (
    candidate_work_dir,
    finish_attempt,
    get_candidate,
    mark_candidate_valid,
    park_candidate,
    register_artifact,
    update_candidate_artifacts,
)
from app.modules.bluecad.loop import _run_simulation_stage
from app.modules.bluecad.models import BluecadCandidateRead, BluecadLoopConfig
from app.modules.bluecad.service import build_geometry_spec
from app.modules.bluecad.spec import SpecValidationError, canonical_json, canonicalize_geometry_spec
from app.modules.events.service import utc_now
from app.modules.runner.input_contracts import canonicalize_input_contract
from app.modules.runner.safety import sha256_file
from app.modules.runner.service import (
    BUNDLED_BLUEREV_PROCESS0_LABEL,
    CALC_V0_IMPLEMENTATION_KIND,
    _bluerev_process0_contract_path,
    _bluerev_process0_script_path,
)

TRANSFORMATION_VERSION = "bluerev_047_m0_tube_proxy_v0_1"
IMPLEMENTATION_VERSION = "cad_link_047_v0_1"
GEOMETRY_INPUTS = ("tube_length", "tube_inner_diameter", "tube_outer_diameter")
ABS_DIAMETER_TOL_MM = 1e-9
REL_TOL = 1e-12
ABS_VOLUME_TOL_M3 = 1e-15
ABS_AREA_TOL_M2 = 1e-15
ARTIFACT_PRODUCER = "Generated by deterministic CAD-LINK-0 from a verified bundled-047 run."


class CadLinkError(ValueError):
    def __init__(self, code: str, message: str, *, status_code: int) -> None:
        super().__init__(message)
        self.code = code
        self.message = message
        self.status_code = status_code


class CadLinkPreviewRequest(BaseModel):
    model_config = ConfigDict(extra="forbid", strict=True)

    source_simulation_run_id: str = Field(min_length=1, max_length=256)
    analysis_spec: dict[str, Any] | None = None

    @model_validator(mode="after")
    def _validate_analysis_spec(self) -> CadLinkPreviewRequest:
        if self.analysis_spec is not None:
            BluecadLoopConfig(analysis_spec=self.analysis_spec)
        return self


class CadLinkExecuteRequest(CadLinkPreviewRequest):
    preview_digest: str = Field(pattern=r"^sha256:[0-9a-f]{64}$")


class CadLinkExecuteResponse(BaseModel):
    candidate: BluecadCandidateRead
    link_id: str
    preview_digest: str
    replayed: bool


def preview_cad_link_047(workspace_id: str, payload: CadLinkPreviewRequest) -> dict[str, Any]:
    """Resolve and reconcile the exact one-tube proxy without side effects."""

    with open_sqlite_connection() as connection:
        connection.execute("PRAGMA query_only = ON")
        connection.execute("BEGIN")
        try:
            preview = _build_preview(connection, workspace_id, payload)
        finally:
            connection.rollback()
    return preview


def execute_cad_link_047(workspace_id: str, payload: CadLinkExecuteRequest) -> CadLinkExecuteResponse:
    """Execute one digest-bound preview and return the idempotent linked candidate."""

    preview_request = CadLinkPreviewRequest(
        source_simulation_run_id=payload.source_simulation_run_id,
        analysis_spec=payload.analysis_spec,
    )
    preview = preview_cad_link_047(workspace_id, preview_request)
    if preview["preview_digest"] != payload.preview_digest:
        raise CadLinkError(
            "cad_link_preview_stale",
            "The CAD-link preview no longer matches current source state.",
            status_code=409,
        )

    _ensure_link_schema()
    existing = _load_existing_link(workspace_id, payload.preview_digest)
    if existing is not None:
        return _replay_response(workspace_id, existing, preview)

    candidate_id = str(uuid4())
    attempt_id = str(uuid4())
    link_id = str(uuid4())
    now = utc_now()
    brief = f"Deterministic bundled-047 M0 tube proxy from simulation run {payload.source_simulation_run_id}."
    brief_digest = "sha256:" + hashlib.sha256(brief.encode("utf-8")).hexdigest()

    try:
        with open_sqlite_connection() as connection:
            connection.execute("BEGIN IMMEDIATE")
            current = _build_preview(connection, workspace_id, preview_request)
            if current["preview_digest"] != payload.preview_digest:
                raise CadLinkError(
                    "cad_link_preview_stale",
                    "The CAD-link preview changed before execution.",
                    status_code=409,
                )
            row = connection.execute(
                "SELECT * FROM bluecad_cad_links WHERE workspace_id = ? AND preview_digest = ?",
                (workspace_id, payload.preview_digest),
            ).fetchone()
            if row is not None:
                connection.rollback()
                return _replay_response(workspace_id, dict(row), current)

            connection.execute(
                """
                INSERT INTO bluecad_candidates (
                    id, workspace_id, brief_text, brief_digest, status, parked_reason,
                    spec_artifact_id, glb_artifact_id, report_artifact_id,
                    promoted_decision_id, origin, parent_candidate_id,
                    loop_config_json, created_at, updated_at, notes
                ) VALUES (?, ?, ?, ?, 'generating', NULL, NULL, NULL, NULL, NULL,
                    'process_linked', NULL, '{}', ?, ?, ?)
                """,
                (
                    candidate_id,
                    workspace_id,
                    brief,
                    brief_digest,
                    now,
                    now,
                    f"CAD-LINK transformation={TRANSFORMATION_VERSION}; source_simulation_run_id={payload.source_simulation_run_id}",
                ),
            )
            connection.execute(
                """
                INSERT INTO bluecad_attempts (
                    id, candidate_id, attempt_no, route_class, proposal_ai_job_id,
                    proposal_outcome, build_outcome, validation_verdict,
                    spec_artifact_id, report_artifact_id, manifest_artifact_id,
                    started_at, finished_at, error_detail_json
                ) VALUES (?, ?, 1, 'deterministic:cad_link:047', NULL,
                    'not_applicable', NULL, NULL, NULL, NULL, NULL, ?, NULL, NULL)
                """,
                (attempt_id, candidate_id, now),
            )
            connection.execute(
                """
                INSERT INTO bluecad_cad_links (
                    id, workspace_id, source_simulation_run_id, source_runner_job_id,
                    child_candidate_id, transformation_version, source_snapshot_json,
                    source_snapshot_digest, source_model_identity_json,
                    source_model_identity_digest, analysis_contract_digest,
                    preview_digest, resolved_spec_digest, reconciliation_json,
                    reconciliation_digest, created_at
                ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                """,
                (
                    link_id,
                    workspace_id,
                    payload.source_simulation_run_id,
                    preview["source_runner_job_id"],
                    candidate_id,
                    TRANSFORMATION_VERSION,
                    canonical_json(preview["source_snapshot"]),
                    preview["source_snapshot_digest"],
                    canonical_json(preview["source_model_identity"]),
                    preview["source_model_identity_digest"],
                    preview["analysis_contract_digest"],
                    preview["preview_digest"],
                    preview["resolved_spec_digest"],
                    canonical_json(preview["reconciliation"]),
                    preview["reconciliation_digest"],
                    now,
                ),
            )
            connection.commit()
    except sqlite3.IntegrityError:
        existing = _load_existing_link(workspace_id, payload.preview_digest)
        if existing is not None:
            return _replay_response(workspace_id, existing, preview)
        raise CadLinkError(
            "cad_link_persistence_failed",
            "The CAD-link record could not be created coherently.",
            status_code=500,
        ) from None

    out_dir = candidate_work_dir(workspace_id, candidate_id, 1)
    spec_artifact_id: str | None = None
    report_artifact_id: str | None = None
    manifest_artifact_id: str | None = None
    glb_artifact_id: str | None = None
    attempt_finished = False
    try:
        out_dir.mkdir(parents=True, exist_ok=False)
        spec_path = out_dir / "geometry_spec.json"
        spec_path.write_text(canonical_json(preview["resolved_geometry_spec"]) + "\n", encoding="utf-8")
        result = build_geometry_spec(preview["resolved_geometry_spec"], out_dir)
        _append_manifest_reconciliation(result, preview["reconciliation"])
        source_ref = f"bluecad_candidate:{candidate_id}:attempt:1"
        spec_artifact_id = register_artifact(
            workspace_id,
            spec_path,
            role="bluecad_spec",
            source_ref=source_ref,
            producer_notes=ARTIFACT_PRODUCER,
        )
        report_artifact_id = register_artifact(
            workspace_id,
            _require_path(result.report_path, out_dir / "validation_report.json"),
            role="bluecad_report",
            source_ref=source_ref,
            producer_notes=ARTIFACT_PRODUCER,
        )
        if result.manifest_path is not None and result.manifest_path.exists():
            manifest_artifact_id = register_artifact(
                workspace_id,
                result.manifest_path,
                role="bluecad_manifest",
                source_ref=source_ref,
                producer_notes=ARTIFACT_PRODUCER,
            )
        glb_path = out_dir / "model.glb"
        if glb_path.exists():
            glb_artifact_id = register_artifact(
                workspace_id,
                glb_path,
                role="bluecad_glb",
                source_ref=source_ref,
                producer_notes=ARTIFACT_PRODUCER,
            )

        verdict = "pass" if result.report.get("verdict") == "pass" else "fail"
        build_outcome = "ok" if result.verdict != "error" else _build_error_code(result.errors)
        finish_attempt(
            attempt_id,
            proposal_outcome="not_applicable",
            build_outcome=build_outcome,
            validation_verdict=verdict,
            spec_artifact_id=spec_artifact_id,
            report_artifact_id=report_artifact_id,
            manifest_artifact_id=manifest_artifact_id,
            error_detail={"transformation_version": TRANSFORMATION_VERSION},
        )
        attempt_finished = True
        update_candidate_artifacts(
            candidate_id,
            spec_artifact_id=spec_artifact_id,
            glb_artifact_id=glb_artifact_id,
            report_artifact_id=report_artifact_id,
        )
        record_validation_evidence(
            workspace_id,
            candidate_id,
            attempt_id,
            result.report,
            report_artifact_id=report_artifact_id,
        )
        if verdict == "pass":
            mark_candidate_valid(candidate_id)
            _run_simulation_stage(
                workspace_id,
                candidate_id,
                attempt_id,
                1,
                payload.analysis_spec,
                {
                    "result": result,
                    "report": result.report,
                    "spec_artifact_id": spec_artifact_id,
                    "report_artifact_id": report_artifact_id,
                    "manifest_artifact_id": manifest_artifact_id,
                    "glb_artifact_id": glb_artifact_id,
                },
            )
        else:
            park_candidate(candidate_id, "cad_link_failed", notes="Deterministic CAD-link validation failed.")
    except Exception as exc:
        if not attempt_finished:
            _best_effort_finish_failed_attempt(
                attempt_id,
                exc,
                spec_artifact_id=spec_artifact_id,
                report_artifact_id=report_artifact_id,
                manifest_artifact_id=manifest_artifact_id,
            )
        park_candidate(candidate_id, "cad_link_failed", notes=f"cad_link_execution_error={type(exc).__name__}")
        if all(
            artifact_id is None
            for artifact_id in (
                spec_artifact_id,
                report_artifact_id,
                manifest_artifact_id,
                glb_artifact_id,
            )
        ):
            _best_effort_cleanup_unregistered(out_dir)
        raise CadLinkError(
            "cad_link_persistence_failed",
            "The deterministic CAD-link build did not complete coherently.",
            status_code=500,
        ) from exc

    candidate = get_candidate(workspace_id, candidate_id)
    if candidate is None:
        raise CadLinkError(
            "cad_link_persistence_inconsistent",
            "The linked candidate is missing after execution.",
            status_code=500,
        )
    return CadLinkExecuteResponse(
        candidate=candidate,
        link_id=link_id,
        preview_digest=payload.preview_digest,
        replayed=False,
    )


def _build_preview(
    connection: sqlite3.Connection,
    workspace_id: str,
    payload: CadLinkPreviewRequest,
) -> dict[str, Any]:
    if connection.execute("SELECT id FROM workspaces WHERE id = ?", (workspace_id,)).fetchone() is None:
        raise CadLinkError("cad_link_run_not_found", "Workspace or source run was not found.", status_code=404)

    run = connection.execute(
        "SELECT * FROM simulation_runs WHERE id = ? AND workspace_id = ?",
        (payload.source_simulation_run_id, workspace_id),
    ).fetchone()
    if run is None:
        raise CadLinkError("cad_link_run_not_found", "Source simulation run was not found.", status_code=404)
    if str(run["status"]) != "succeeded":
        raise CadLinkError("cad_link_run_not_succeeded", "Source simulation run must have succeeded.", status_code=422)
    _require_fresh(connection, workspace_id, f"simulation_run:{run['id']}", "cad_link_run_stale")

    jobs = connection.execute(
        "SELECT * FROM runner_jobs WHERE simulation_run_id = ? AND workspace_id = ? ORDER BY created_at",
        (run["id"], workspace_id),
    ).fetchall()
    if len(jobs) != 1 or str(jobs[0]["status"]) != "succeeded":
        raise CadLinkError(
            "cad_link_runner_job_invalid",
            "Source run must have exactly one succeeded runner job.",
            status_code=422,
        )
    job = jobs[0]

    model = connection.execute(
        """
        SELECT mv.*, a.sha256 AS script_sha256
        FROM model_versions mv
        JOIN artifacts a ON a.id = mv.implementation_artifact_id
        WHERE mv.id = ? AND mv.workspace_id = ?
        """,
        (run["model_version_id"], workspace_id),
    ).fetchone()
    if model is None:
        raise CadLinkError("cad_link_model_identity_mismatch", "Bundled-047 model identity is missing.", status_code=422)
    model_identity = _verify_model_identity(model, job)

    input_payload = _json_object(run["input_payload"], "cad_link_numeric_invalid")
    output_payload = _json_object(run["output_payload"], "cad_link_reconciliation_failed")
    outputs = output_payload.get("outputs")
    if not isinstance(outputs, dict):
        raise CadLinkError(
            "cad_link_reconciliation_failed",
            "Source run is missing canonical 047 outputs.",
            status_code=422,
        )

    source_snapshot: dict[str, Any] = {}
    decimals: dict[str, Decimal] = {}
    parameter_ids: set[str] = set()
    for name in GEOMETRY_INPUTS:
        item = input_payload.get(name)
        if not isinstance(item, dict):
            raise CadLinkError(
                "cad_link_parameter_binding_missing",
                "A required geometry binding is missing from the source run.",
                status_code=422,
            )
        parameter_id = item.get("source_parameter_id")
        if not isinstance(parameter_id, str) or not parameter_id:
            raise CadLinkError(
                "cad_link_parameter_binding_missing",
                "All geometry inputs must be backed by canonical Parameters.",
                status_code=422,
            )
        if parameter_id in parameter_ids:
            raise CadLinkError(
                "cad_link_parameter_snapshot_mismatch",
                "One Parameter cannot drive incompatible geometry input names.",
                status_code=422,
            )
        parameter_ids.add(parameter_id)
        parameter = connection.execute(
            "SELECT * FROM parameters WHERE id = ? AND workspace_id = ?",
            (parameter_id, workspace_id),
        ).fetchone()
        if parameter is None:
            raise CadLinkError("cad_link_parameter_not_found", "A source Parameter was not found.", status_code=404)
        if str(parameter["status"]) != "accepted":
            raise CadLinkError(
                "cad_link_parameter_not_accepted",
                "Geometry source Parameters must be accepted.",
                status_code=422,
            )
        _require_fresh(connection, workspace_id, f"parameter:{parameter_id}", "cad_link_parameter_stale")
        executed_unit = item.get("unit")
        if not isinstance(executed_unit, str):
            raise CadLinkError("cad_link_unit_unsupported", "Geometry input unit is invalid.", status_code=422)
        expected_unit = "m" if name == "tube_length" else "mm"
        if executed_unit != expected_unit or str(parameter["unit"]) != expected_unit:
            raise CadLinkError("cad_link_unit_unsupported", "Geometry input unit is unsupported.", status_code=422)
        executed = _decimal(item.get("value"))
        current = _decimal(parameter["value"])
        if executed != current:
            raise CadLinkError(
                "cad_link_parameter_snapshot_mismatch",
                "A source Parameter changed after the source run.",
                status_code=409,
            )
        decimals[name] = executed
        source_snapshot[name] = {
            "parameter_ref": f"parameter:{parameter_id}",
            "name": str(parameter["name"]),
            "executed_value": _decimal_text(executed),
            "current_value": _decimal_text(current),
            "unit": expected_unit,
            "status": str(parameter["status"]),
            "origin": str(parameter["origin"]),
            "source_ref": parameter["source_ref"],
            "freshness": "fresh",
        }

    length = decimals["tube_length"]
    inner = decimals["tube_inner_diameter"]
    outer = decimals["tube_outer_diameter"]
    if length <= 0 or inner <= 0 or outer <= inner:
        raise CadLinkError("cad_link_geometry_invalid", "Geometry inputs are outside the CAD-link domain.", status_code=422)
    length_mm = length * Decimal(1000)
    wall = (outer - inner) / Decimal(2)
    if wall <= 0 or wall * 2 >= outer:
        raise CadLinkError("cad_link_geometry_invalid", "Derived tube wall is invalid.", status_code=422)

    raw_spec = {
        "spec_version": "bluecad_geometry_spec_v0_1",
        "name": "bluerev_047_m0_tube_proxy",
        "parts": [
            {
                "part_id": "illuminated_tube_proxy",
                "kind": "tube_run",
                "params": {
                    "outer_d": _finite_float(outer),
                    "wall_t": _finite_float(wall),
                    "length": _finite_float(length_mm),
                },
            }
        ],
        "connections": [],
    }
    try:
        resolved_spec = canonicalize_geometry_spec(raw_spec)
    except SpecValidationError as exc:
        raise CadLinkError("cad_link_geometry_invalid", "Resolved GeometrySpec is invalid.", status_code=422) from exc

    reconciliation = _reconcile(resolved_spec, outputs, inner, outer, length)
    if not all(item["passed"] for item in reconciliation["checks"]):
        raise CadLinkError(
            "cad_link_reconciliation_failed",
            "Resolved CAD geometry does not reconcile with the source 047 run.",
            status_code=422,
        )

    source_snapshot_digest = _digest(source_snapshot)
    model_identity_digest = _digest(model_identity)
    reconciliation_digest = _digest(reconciliation)
    analysis_contract_digest = None if payload.analysis_spec is None else _digest(payload.analysis_spec)
    preview_core = {
        "implementation_version": IMPLEMENTATION_VERSION,
        "workspace_id": workspace_id,
        "source_simulation_run_id": str(run["id"]),
        "source_runner_job_id": str(job["id"]),
        "run_status": str(run["status"]),
        "runner_status": str(job["status"]),
        "source_input_payload_digest": _digest(input_payload),
        "source_output_payload_digest": _digest(output_payload),
        "geometry_spec_version": str(resolved_spec["spec_version"]),
        "source_model_identity": model_identity,
        "source_model_identity_digest": model_identity_digest,
        "source_snapshot": source_snapshot,
        "source_snapshot_digest": source_snapshot_digest,
        "transformation_version": TRANSFORMATION_VERSION,
        "transformed_values": {
            "length_mm": _decimal_text(length_mm),
            "outer_d_mm": _decimal_text(outer),
            "wall_t_mm": _decimal_text(wall),
        },
        "resolved_geometry_spec": resolved_spec,
        "resolved_spec_digest": str(resolved_spec["spec_id"]),
        "reconciliation": reconciliation,
        "reconciliation_digest": reconciliation_digest,
        "analysis_contract_digest": analysis_contract_digest,
    }
    return {**preview_core, "preview_digest": _digest(preview_core)}


def _verify_model_identity(model: sqlite3.Row, job: sqlite3.Row) -> dict[str, Any]:
    expected_script_sha = sha256_file(_bluerev_process0_script_path())
    contract = json.loads(_bluerev_process0_contract_path().read_text(encoding="utf-8"))
    _payload, expected_contract_sha, _normalized = canonicalize_input_contract(contract)
    identity = {
        "model_version_id": str(model["id"]),
        "version_label": str(model["version_label"]),
        "implementation_kind": str(model["implementation_kind"]),
        "script_sha256": str(model["script_sha256"]),
        "input_contract_sha256": model["input_contract_sha256"],
    }
    valid = (
        identity["version_label"] == BUNDLED_BLUEREV_PROCESS0_LABEL
        and identity["implementation_kind"] == CALC_V0_IMPLEMENTATION_KIND
        and identity["script_sha256"] == expected_script_sha
        and identity["input_contract_sha256"] == expected_contract_sha
        and str(job["implementation_kind"]) == CALC_V0_IMPLEMENTATION_KIND
        and str(job["script_sha256"]) == expected_script_sha
    )
    if not valid:
        raise CadLinkError(
            "cad_link_model_identity_mismatch",
            "Source run is not the current verified bundled-047 implementation.",
            status_code=422,
        )
    return identity


def _reconcile(
    spec: dict[str, Any],
    outputs: dict[str, Any],
    expected_inner: Decimal,
    expected_outer: Decimal,
    expected_length_m: Decimal,
) -> dict[str, Any]:
    params = spec["parts"][0]["params"]
    outer_mm = float(params["outer_d"])
    wall_mm = float(params["wall_t"])
    length_mm = float(params["length"])
    inner_mm = outer_mm - 2.0 * wall_mm
    liquid_volume = math.pi * (inner_mm / 1000.0) ** 2 / 4.0 * (length_mm / 1000.0)
    external_area = math.pi * (outer_mm / 1000.0) * (length_mm / 1000.0)
    solid_material_volume = math.pi / 4.0 * (outer_mm**2 - inner_mm**2) * length_mm
    source_volume = _output_value(outputs, "tube_liquid_volume", "m3")
    source_area = _output_value(outputs, "external_illuminated_area_proxy", "m2")
    checks = [
        _check("inner_diameter_mm", inner_mm, float(expected_inner), ABS_DIAMETER_TOL_MM),
        _check("outer_diameter_mm", outer_mm, float(expected_outer), ABS_DIAMETER_TOL_MM),
        _check("length_m", length_mm / 1000.0, float(expected_length_m), 1e-12),
        _check("tube_liquid_volume_m3", liquid_volume, source_volume, ABS_VOLUME_TOL_M3),
        _check("external_illuminated_area_m2", external_area, source_area, ABS_AREA_TOL_M2),
    ]
    return {
        "relative_tolerance": REL_TOL,
        "checks": checks,
        "cad_values": {
            "inner_diameter_mm": inner_mm,
            "outer_diameter_mm": outer_mm,
            "length_m": length_mm / 1000.0,
            "tube_liquid_volume_m3": liquid_volume,
            "external_illuminated_area_m2": external_area,
            "solid_material_volume_mm3": solid_material_volume,
        },
    }


def _append_manifest_reconciliation(result: Any, reconciliation: dict[str, Any]) -> None:
    if result.manifest is None:
        return
    assembly = result.manifest.get("assembly")
    actual = None if not isinstance(assembly, dict) else assembly.get("total_volume_mm3")
    expected = reconciliation["cad_values"]["solid_material_volume_mm3"]
    passed = (
        isinstance(actual, (int, float))
        and not isinstance(actual, bool)
        and math.isfinite(float(actual))
        and math.isclose(float(actual), float(expected), rel_tol=REL_TOL, abs_tol=1e-6)
    )
    result.report.setdefault("checks", []).append(
        {
            "id": "CAD_LINK_SOLID_VOLUME_RECONCILIATION",
            "tier": 2,
            "status": "pass" if passed else "fail",
            "detail": {
                "actual_manifest_solid_volume_mm3": actual,
                "expected_annular_solid_volume_mm3": expected,
                "relative_tolerance": REL_TOL,
                "absolute_tolerance_mm3": 1e-6,
            },
        }
    )
    if not passed:
        result.report["verdict"] = "fail"
    if result.report_path is not None:
        result.report_path.write_text(
            json.dumps(result.report, indent=2, sort_keys=True) + "\n",
            encoding="utf-8",
        )


def _check(name: str, observed: float, expected: float, absolute_tolerance: float) -> dict[str, Any]:
    passed = math.isclose(observed, expected, rel_tol=REL_TOL, abs_tol=absolute_tolerance)
    return {
        "name": name,
        "observed": observed,
        "expected": expected,
        "absolute_tolerance": absolute_tolerance,
        "passed": passed,
    }


def _output_value(outputs: dict[str, Any], name: str, unit: str) -> float:
    item = outputs.get(name)
    if not isinstance(item, dict) or item.get("unit") != unit:
        raise CadLinkError(
            "cad_link_reconciliation_failed",
            "Source run output contract is incomplete.",
            status_code=422,
        )
    value = item.get("value")
    if isinstance(value, bool):
        raise CadLinkError("cad_link_reconciliation_failed", "Source run output is invalid.", status_code=422)
    try:
        number = float(value)
    except (TypeError, ValueError, OverflowError) as exc:
        raise CadLinkError("cad_link_reconciliation_failed", "Source run output is invalid.", status_code=422) from exc
    if not math.isfinite(number):
        raise CadLinkError("cad_link_reconciliation_failed", "Source run output is invalid.", status_code=422)
    return number


def _require_fresh(connection: sqlite3.Connection, workspace_id: str, record_ref: str, code: str) -> None:
    row = connection.execute(
        "SELECT 1 FROM freshness_marks WHERE workspace_id = ? AND record_ref = ? LIMIT 1",
        (workspace_id, record_ref),
    ).fetchone()
    if row is not None:
        raise CadLinkError(code, "A CAD-link source record is stale.", status_code=409)


def _json_object(raw: Any, code: str) -> dict[str, Any]:
    try:
        value = json.loads(str(raw))
    except (TypeError, ValueError, json.JSONDecodeError) as exc:
        raise CadLinkError(code, "Stored source JSON is invalid.", status_code=422) from exc
    if not isinstance(value, dict):
        raise CadLinkError(code, "Stored source JSON must be an object.", status_code=422)
    return value


def _decimal(value: Any) -> Decimal:
    if isinstance(value, bool) or value is None:
        raise CadLinkError("cad_link_numeric_invalid", "Geometry values must be finite numbers.", status_code=422)
    try:
        number = Decimal(str(value))
    except (InvalidOperation, ValueError) as exc:
        raise CadLinkError("cad_link_numeric_invalid", "Geometry values must be finite numbers.", status_code=422) from exc
    if not number.is_finite():
        raise CadLinkError("cad_link_numeric_invalid", "Geometry values must be finite numbers.", status_code=422)
    return number


def _decimal_text(value: Decimal) -> str:
    return format(value.normalize(), "f")


def _finite_float(value: Decimal) -> float:
    number = float(value)
    if not math.isfinite(number):
        raise CadLinkError("cad_link_numeric_invalid", "Geometry value is not representable.", status_code=422)
    return number


def _digest(value: Any) -> str:
    payload = canonical_json(value)
    return "sha256:" + hashlib.sha256(payload.encode("utf-8")).hexdigest()


def _ensure_link_schema() -> None:
    with open_sqlite_connection() as connection:
        for statement in CAD_LINK_SCHEMA_STATEMENTS:
            connection.execute(statement)
        for statement in CAD_LINK_SCHEMA_INDEX_STATEMENTS:
            connection.execute(statement)
        connection.commit()


def _load_existing_link(workspace_id: str, preview_digest: str) -> dict[str, Any] | None:
    with open_sqlite_connection() as connection:
        row = connection.execute(
            "SELECT * FROM bluecad_cad_links WHERE workspace_id = ? AND preview_digest = ?",
            (workspace_id, preview_digest),
        ).fetchone()
    return None if row is None else dict(row)


def _replay_response(workspace_id: str, row: dict[str, Any], preview: dict[str, Any]) -> CadLinkExecuteResponse:
    expected = {
        "source_simulation_run_id": preview["source_simulation_run_id"],
        "source_runner_job_id": preview["source_runner_job_id"],
        "transformation_version": preview["transformation_version"],
        "source_snapshot_digest": preview["source_snapshot_digest"],
        "source_model_identity_digest": preview["source_model_identity_digest"],
        "analysis_contract_digest": preview["analysis_contract_digest"],
        "preview_digest": preview["preview_digest"],
        "resolved_spec_digest": preview["resolved_spec_digest"],
        "reconciliation_digest": preview["reconciliation_digest"],
    }
    if any(str(row[key]) != str(value) for key, value in expected.items()):
        raise CadLinkError(
            "cad_link_persistence_inconsistent",
            "Stored CAD-link digests are inconsistent.",
            status_code=409,
        )
    candidate = get_candidate(workspace_id, str(row["child_candidate_id"]))
    if candidate is None:
        raise CadLinkError(
            "cad_link_persistence_inconsistent",
            "Stored CAD-link candidate is missing.",
            status_code=409,
        )
    return CadLinkExecuteResponse(
        candidate=candidate,
        link_id=str(row["id"]),
        preview_digest=str(row["preview_digest"]),
        replayed=True,
    )


def _build_error_code(errors: list[dict[str, Any]]) -> str:
    if not errors:
        return "error"
    code = errors[0].get("code")
    return str(code).lower() if code else "error"


def _require_path(path: Path | None, fallback: Path) -> Path:
    resolved = path or fallback
    if not resolved.exists():
        raise RuntimeError("expected deterministic BLUECAD artifact is missing")
    return resolved


def _best_effort_finish_failed_attempt(
    attempt_id: str,
    exc: Exception,
    *,
    spec_artifact_id: str | None,
    report_artifact_id: str | None,
    manifest_artifact_id: str | None,
) -> None:
    try:
        finish_attempt(
            attempt_id,
            proposal_outcome="not_applicable",
            build_outcome="cad_link_execution_error",
            validation_verdict="fail",
            spec_artifact_id=spec_artifact_id,
            report_artifact_id=report_artifact_id,
            manifest_artifact_id=manifest_artifact_id,
            error_detail={
                "transformation_version": TRANSFORMATION_VERSION,
                "error_type": type(exc).__name__,
            },
        )
    except Exception:
        return


def _best_effort_cleanup_unregistered(out_dir: Path) -> None:
    try:
        if out_dir.exists():
            shutil.rmtree(out_dir)
    except OSError:
        return
