"""Digest-bound execution lifecycle for the exact bundled-072 CAD link."""

from __future__ import annotations

import hashlib
import json
import math
import shutil
import sqlite3
from collections.abc import Mapping
from pathlib import Path
from typing import Any
from uuid import uuid4

from app.core.database import open_sqlite_connection
from app.modules.bluecad.cad_link import CadLinkError, CadLinkExecuteResponse
from app.modules.bluecad.cad_link_topology import (
    BUILD_TIMEOUT_SECONDS,
    CadLink072ExecuteRequest,
    CadLink072PreviewRequest,
    _build_preview,
    preview_cad_link_072,
)
from app.modules.bluecad.cad_link_topology_contract import TRANSFORMATION_VERSION
from app.modules.bluecad.cad_link_topology_source import digest
from app.modules.bluecad.evidence import record_validation_evidence
from app.modules.bluecad.ledger import (
    candidate_work_dir,
    finish_attempt,
    get_candidate,
    mark_candidate_valid,
    park_candidate,
    register_artifact,
    update_candidate_artifacts,
)
from app.modules.bluecad.loop import _run_simulation_stage
from app.modules.bluecad.service import build_geometry_spec
from app.modules.bluecad.spec import canonical_json
from app.modules.events.service import utc_now

ROUTE_CLASS = "deterministic:cad_link:072"
ARTIFACT_PRODUCER = (
    "Generated by deterministic CAD-LINK-1 from a verified bundled-072 topology run."
)
REPRESENTATION_NOTES = (
    "represented: common tubing, split/merge manifolds, repeated branch tubing; "
    "not represented: pump, reservoir vessel, supports, floats, anchors, "
    "instrumentation; CAD boundary: open supply inlet and open return outlet"
)


def execute_cad_link_072(
    workspace_id: str,
    payload: CadLink072ExecuteRequest,
) -> CadLinkExecuteResponse:
    """Execute one current digest-bound 072 preview without alternate authority."""

    preview_request = CadLink072PreviewRequest(
        source_simulation_run_id=payload.source_simulation_run_id,
        layout_spec=payload.layout_spec,
        analysis_spec=payload.analysis_spec,
    )
    preview = _preview_for_execute(workspace_id, preview_request)
    _require_preview_digest(preview, payload.preview_digest)

    existing = _load_existing_link(workspace_id, payload.preview_digest)
    if existing is not None:
        return _replay_response(workspace_id, existing, preview)

    candidate_id = str(uuid4())
    attempt_id = str(uuid4())
    link_id = str(uuid4())
    now = utc_now()
    brief = (
        "Deterministic bundled-072 planar tubing/manifold representation from "
        f"simulation run {payload.source_simulation_run_id}."
    )
    brief_digest = "sha256:" + hashlib.sha256(brief.encode("utf-8")).hexdigest()

    try:
        with open_sqlite_connection() as connection:
            connection.execute("BEGIN IMMEDIATE")
            try:
                current = _preview_from_connection(
                    connection,
                    workspace_id,
                    preview_request,
                )
                _require_preview_digest(current, payload.preview_digest)
                row = connection.execute(
                    """
                    SELECT * FROM bluecad_cad_links
                    WHERE workspace_id = ? AND preview_digest = ?
                    """,
                    (workspace_id, payload.preview_digest),
                ).fetchone()
                if row is not None:
                    connection.rollback()
                    return _replay_response(workspace_id, dict(row), current)

                connection.execute(
                    """
                    INSERT INTO bluecad_candidates (
                        id, workspace_id, brief_text, brief_digest, status,
                        parked_reason, spec_artifact_id, glb_artifact_id,
                        report_artifact_id, promoted_decision_id, origin,
                        parent_candidate_id, loop_config_json, created_at,
                        updated_at, notes
                    ) VALUES (?, ?, ?, ?, 'generating', NULL, NULL, NULL,
                        NULL, NULL, 'process_linked', NULL, '{}', ?, ?, ?)
                    """,
                    (
                        candidate_id,
                        workspace_id,
                        brief,
                        brief_digest,
                        now,
                        now,
                        (
                            f"CAD-LINK transformation={TRANSFORMATION_VERSION}; "
                            f"source_simulation_run_id={payload.source_simulation_run_id}; "
                            f"{REPRESENTATION_NOTES}"
                        ),
                    ),
                )
                connection.execute(
                    """
                    INSERT INTO bluecad_attempts (
                        id, candidate_id, attempt_no, route_class,
                        proposal_ai_job_id, proposal_outcome, build_outcome,
                        validation_verdict, spec_artifact_id,
                        report_artifact_id, manifest_artifact_id, started_at,
                        finished_at, error_detail_json
                    ) VALUES (?, ?, 1, ?, NULL, 'not_applicable', NULL,
                        NULL, NULL, NULL, NULL, ?, NULL, NULL)
                    """,
                    (attempt_id, candidate_id, ROUTE_CLASS, now),
                )
                connection.execute(
                    """
                    INSERT INTO bluecad_cad_links (
                        id, workspace_id, source_simulation_run_id,
                        source_runner_job_id, child_candidate_id,
                        transformation_version, source_snapshot_json,
                        source_snapshot_digest, source_model_identity_json,
                        source_model_identity_digest, analysis_contract_digest,
                        preview_digest, resolved_spec_digest,
                        reconciliation_json, reconciliation_digest, created_at
                    ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                    """,
                    (
                        link_id,
                        workspace_id,
                        current["source_simulation_run_id"],
                        current["source_runner_job_id"],
                        candidate_id,
                        current["transformation_version"],
                        canonical_json(current["source_snapshot"]),
                        current["source_snapshot_digest"],
                        canonical_json(current["source_model_identity"]),
                        current["source_model_identity_digest"],
                        current["analysis_contract_digest"],
                        current["preview_digest"],
                        current["resolved_spec_digest"],
                        canonical_json(current["reconciliation"]),
                        current["reconciliation_digest"],
                        now,
                    ),
                )
                connection.commit()
                preview = current
            except Exception:
                connection.rollback()
                raise
    except sqlite3.IntegrityError:
        existing = _load_existing_link(workspace_id, payload.preview_digest)
        if existing is not None:
            return _replay_response(workspace_id, existing, preview)
        raise CadLinkError(
            "cad_link_persistence_failed",
            "The topology CAD-link record could not be created coherently.",
            status_code=500,
        ) from None

    out_dir = candidate_work_dir(workspace_id, candidate_id, 1)
    spec_artifact_id: str | None = None
    report_artifact_id: str | None = None
    manifest_artifact_id: str | None = None
    glb_artifact_id: str | None = None
    attempt_finished = False
    try:
        out_dir.mkdir(parents=True, exist_ok=False)
        spec_path = out_dir / "geometry_spec.json"
        spec_path.write_text(
            canonical_json(preview["resolved_spec"]) + "\n",
            encoding="utf-8",
        )
        result = build_geometry_spec(
            preview["resolved_spec"],
            out_dir,
            timeout_s=BUILD_TIMEOUT_SECONDS,
        )
        _append_topology_reconciliation(result, preview["reconciliation"])
        source_ref = f"bluecad_candidate:{candidate_id}:attempt:1"
        spec_artifact_id = register_artifact(
            workspace_id,
            spec_path,
            role="bluecad_spec",
            source_ref=source_ref,
            producer_notes=ARTIFACT_PRODUCER,
        )
        report_artifact_id = register_artifact(
            workspace_id,
            _require_path(result.report_path, out_dir / "validation_report.json"),
            role="bluecad_report",
            source_ref=source_ref,
            producer_notes=ARTIFACT_PRODUCER,
        )
        if result.manifest_path is not None and result.manifest_path.exists():
            manifest_artifact_id = register_artifact(
                workspace_id,
                result.manifest_path,
                role="bluecad_manifest",
                source_ref=source_ref,
                producer_notes=ARTIFACT_PRODUCER,
            )
        glb_path = out_dir / "model.glb"
        if glb_path.exists():
            glb_artifact_id = register_artifact(
                workspace_id,
                glb_path,
                role="bluecad_glb",
                source_ref=source_ref,
                producer_notes=ARTIFACT_PRODUCER,
            )

        verdict = "pass" if result.report.get("verdict") == "pass" else "fail"
        build_outcome = (
            "ok" if result.verdict != "error" else _build_error_code(result.errors)
        )
        finish_attempt(
            attempt_id,
            proposal_outcome="not_applicable",
            build_outcome=build_outcome,
            validation_verdict=verdict,
            spec_artifact_id=spec_artifact_id,
            report_artifact_id=report_artifact_id,
            manifest_artifact_id=manifest_artifact_id,
            error_detail={
                "transformation_version": TRANSFORMATION_VERSION,
                "preview_digest": preview["preview_digest"],
            },
        )
        attempt_finished = True
        update_candidate_artifacts(
            candidate_id,
            spec_artifact_id=spec_artifact_id,
            glb_artifact_id=glb_artifact_id,
            report_artifact_id=report_artifact_id,
        )
        record_validation_evidence(
            workspace_id,
            candidate_id,
            attempt_id,
            result.report,
            report_artifact_id=report_artifact_id,
        )
        if verdict == "pass":
            mark_candidate_valid(candidate_id)
            _run_simulation_stage(
                workspace_id,
                candidate_id,
                attempt_id,
                1,
                payload.analysis_spec,
                {
                    "result": result,
                    "report": result.report,
                    "spec_artifact_id": spec_artifact_id,
                    "report_artifact_id": report_artifact_id,
                    "manifest_artifact_id": manifest_artifact_id,
                    "glb_artifact_id": glb_artifact_id,
                },
                producer_notes=ARTIFACT_PRODUCER,
            )
        else:
            park_candidate(
                candidate_id,
                "cad_link_failed",
                notes="Deterministic topology CAD-link validation failed.",
            )
    except Exception as exc:
        if not attempt_finished:
            _best_effort_finish_failed_attempt(
                attempt_id,
                exc,
                spec_artifact_id=spec_artifact_id,
                report_artifact_id=report_artifact_id,
                manifest_artifact_id=manifest_artifact_id,
            )
        park_candidate(
            candidate_id,
            "cad_link_failed",
            notes=f"cad_link_execution_error={type(exc).__name__}; {REPRESENTATION_NOTES}",
        )
        if all(
            artifact_id is None
            for artifact_id in (
                spec_artifact_id,
                report_artifact_id,
                manifest_artifact_id,
                glb_artifact_id,
            )
        ):
            _best_effort_cleanup_unregistered(out_dir)
        raise CadLinkError(
            "cad_link_persistence_failed",
            "The deterministic topology CAD-link build did not complete coherently.",
            status_code=500,
        ) from exc

    candidate = get_candidate(workspace_id, candidate_id)
    if candidate is None:
        raise CadLinkError(
            "cad_link_persistence_inconsistent",
            "The linked topology candidate is missing after execution.",
            status_code=500,
        )
    return CadLinkExecuteResponse(
        candidate=candidate,
        link_id=link_id,
        preview_digest=payload.preview_digest,
        replayed=False,
    )


def _preview_for_execute(
    workspace_id: str,
    request: CadLink072PreviewRequest,
) -> dict[str, Any]:
    try:
        return preview_cad_link_072(workspace_id, request)
    except CadLinkError as exc:
        if exc.code.startswith("cad_link_kernel_"):
            raise
        raise _preview_stale() from exc


def _preview_from_connection(
    connection: sqlite3.Connection,
    workspace_id: str,
    request: CadLink072PreviewRequest,
) -> dict[str, Any]:
    try:
        return _build_preview(connection, workspace_id, request)
    except CadLinkError as exc:
        if exc.code.startswith("cad_link_kernel_"):
            raise
        raise _preview_stale() from exc


def _require_preview_digest(preview: Mapping[str, Any], expected: str) -> None:
    if preview.get("preview_digest") != expected:
        raise _preview_stale()


def _preview_stale() -> CadLinkError:
    return CadLinkError(
        "cad_link_preview_stale",
        "The topology CAD-link preview no longer matches current authority.",
        status_code=409,
    )


def _load_existing_link(
    workspace_id: str,
    preview_digest: str,
) -> dict[str, Any] | None:
    with open_sqlite_connection() as connection:
        row = connection.execute(
            """
            SELECT * FROM bluecad_cad_links
            WHERE workspace_id = ? AND preview_digest = ?
            """,
            (workspace_id, preview_digest),
        ).fetchone()
    return None if row is None else dict(row)


def _replay_response(
    workspace_id: str,
    row: Mapping[str, Any],
    preview: Mapping[str, Any],
) -> CadLinkExecuteResponse:
    expected = {
        "source_simulation_run_id": preview["source_simulation_run_id"],
        "source_runner_job_id": preview["source_runner_job_id"],
        "transformation_version": preview["transformation_version"],
        "source_snapshot_digest": preview["source_snapshot_digest"],
        "source_model_identity_digest": preview["source_model_identity_digest"],
        "analysis_contract_digest": preview["analysis_contract_digest"],
        "preview_digest": preview["preview_digest"],
        "resolved_spec_digest": preview["resolved_spec_digest"],
        "reconciliation_digest": preview["reconciliation_digest"],
    }
    if any(row.get(key) != value for key, value in expected.items()):
        raise _persistence_inconsistent()

    payloads = (
        (
            "source_snapshot_json",
            "source_snapshot_digest",
            preview["source_snapshot"],
        ),
        (
            "source_model_identity_json",
            "source_model_identity_digest",
            preview["source_model_identity"],
        ),
        (
            "reconciliation_json",
            "reconciliation_digest",
            preview["reconciliation"],
        ),
    )
    for json_field, digest_field, current_value in payloads:
        stored = _json_object(row.get(json_field))
        if (
            digest(stored) != row.get(digest_field)
            or stored != current_value
        ):
            raise _persistence_inconsistent()

    candidate = get_candidate(workspace_id, str(row["child_candidate_id"]))
    if candidate is None:
        raise _persistence_inconsistent()
    return CadLinkExecuteResponse(
        candidate=candidate,
        link_id=str(row["id"]),
        preview_digest=str(row["preview_digest"]),
        replayed=True,
    )


def _json_object(raw: Any) -> dict[str, Any]:
    try:
        value = json.loads(str(raw), parse_constant=_reject_constant)
    except (TypeError, ValueError, json.JSONDecodeError) as exc:
        raise _persistence_inconsistent() from exc
    if not isinstance(value, dict):
        raise _persistence_inconsistent()
    return value


def _reject_constant(value: str) -> object:
    raise ValueError(value)


def _persistence_inconsistent() -> CadLinkError:
    return CadLinkError(
        "cad_link_persistence_inconsistent",
        "Stored topology CAD-link evidence is inconsistent.",
        status_code=409,
    )


def _append_topology_reconciliation(result: Any, reconciliation: Mapping[str, Any]) -> None:
    process = reconciliation.get("process_cad_reconciliation")
    if not isinstance(process, Mapping):
        raise RuntimeError("topology reconciliation payload is missing")
    checks = process.get("checks")
    all_process_checks_pass = isinstance(checks, list) and all(
        isinstance(check, Mapping) and check.get("passed") is True
        for check in checks
    )
    cad_metrics = process.get("cad_only_metrics")
    expected_material_volume = (
        cad_metrics.get("assembly_material_volume_mm3")
        if isinstance(cad_metrics, Mapping)
        else None
    )
    assembly = result.manifest.get("assembly") if isinstance(result.manifest, dict) else None
    actual_material_volume = (
        assembly.get("total_volume_mm3") if isinstance(assembly, Mapping) else None
    )
    material_volume_pass = (
        _finite_number(actual_material_volume)
        and _finite_number(expected_material_volume)
        and math.isclose(
            float(actual_material_volume),
            float(expected_material_volume),
            rel_tol=1e-9,
            abs_tol=1e-6,
        )
    )
    passed = all_process_checks_pass and material_volume_pass
    result.report.setdefault("checks", []).append(
        {
            "id": "CAD_LINK_072_PROCESS_CAD_RECONCILIATION",
            "tier": 2,
            "status": "pass" if passed else "fail",
            "detail": {
                "reconciliation_digest": digest(reconciliation),
                "all_process_checks_pass": all_process_checks_pass,
                "actual_manifest_material_volume_mm3": actual_material_volume,
                "expected_preflight_material_volume_mm3": expected_material_volume,
                "represented_component_inventory": reconciliation.get(
                    "component_inventory"
                ),
                "external_boundaries": reconciliation.get("external_boundaries"),
            },
        }
    )
    if not passed:
        result.report["verdict"] = "fail"
    if result.report_path is not None:
        result.report_path.write_text(
            json.dumps(result.report, indent=2, sort_keys=True) + "\n",
            encoding="utf-8",
        )


def _finite_number(value: Any) -> bool:
    return (
        isinstance(value, int | float)
        and not isinstance(value, bool)
        and math.isfinite(float(value))
    )


def _build_error_code(errors: list[dict[str, Any]]) -> str:
    if not errors:
        return "error"
    code = errors[0].get("code")
    return str(code).lower() if code else "error"


def _require_path(path: Path | None, fallback: Path) -> Path:
    resolved = path or fallback
    if not resolved.exists():
        raise RuntimeError("expected deterministic BLUECAD artifact is missing")
    return resolved


def _best_effort_finish_failed_attempt(
    attempt_id: str,
    exc: Exception,
    *,
    spec_artifact_id: str | None,
    report_artifact_id: str | None,
    manifest_artifact_id: str | None,
) -> None:
    try:
        finish_attempt(
            attempt_id,
            proposal_outcome="not_applicable",
            build_outcome="cad_link_execution_error",
            validation_verdict="fail",
            spec_artifact_id=spec_artifact_id,
            report_artifact_id=report_artifact_id,
            manifest_artifact_id=manifest_artifact_id,
            error_detail={
                "transformation_version": TRANSFORMATION_VERSION,
                "error_type": type(exc).__name__,
            },
        )
    except Exception:
        return


def _best_effort_cleanup_unregistered(out_dir: Path) -> None:
    try:
        if out_dir.exists():
            shutil.rmtree(out_dir)
    except OSError:
        return
