"""Provider-free BLUECAD candidates from explicit operator template parameters.

A template maps a few bounded millimetre parameters onto one existing
GeometrySpec part kind and then follows the same canonicalization, build,
validation, evidence and export path as the AI loop. No AI call is made.
"""

from __future__ import annotations

import json
import shutil
from pathlib import Path
from typing import Annotated, Any, Literal
from uuid import uuid4

from pydantic import BaseModel, ConfigDict, Field, model_validator

from app.core.database import open_sqlite_connection
from app.modules.bluecad.evidence import record_validation_evidence
from app.modules.bluecad.ledger import (
    _require_workspace,
    brief_digest,
    candidate_work_dir,
    finish_attempt,
    get_candidate,
    mark_candidate_valid,
    park_candidate,
    register_artifact,
    register_export_artifacts,
    update_candidate_artifacts,
)
from app.modules.bluecad.models import BluecadCandidateRead
from app.modules.bluecad.service import build_geometry_spec
from app.modules.bluecad.spec import SpecValidationError, canonical_json, canonicalize_geometry_spec
from app.modules.events.service import utc_now

TEMPLATE_VERSION = "bluecad_template_v0_1"
ARTIFACT_PRODUCER = "Generated by deterministic BLUECAD template from explicit operator parameters."

_STRICT = ConfigDict(extra="forbid", allow_inf_nan=False)
OuterDiameterMm = Annotated[float, Field(ge=2.0, le=1000.0)]
WallMm = Annotated[float, Field(ge=0.5, le=100.0)]
LengthMm = Annotated[float, Field(ge=1.0, le=5000.0)]


class TemplateError(ValueError):
    def __init__(self, code: str, message: str, *, status_code: int) -> None:
        super().__init__(message)
        self.code = code
        self.message = message
        self.status_code = status_code


class TubeTemplateParams(BaseModel):
    model_config = _STRICT

    outer_d_mm: OuterDiameterMm
    wall_t_mm: WallMm
    length_mm: LengthMm

    @model_validator(mode="after")
    def _wall_fits(self) -> TubeTemplateParams:
        if self.wall_t_mm * 2 >= self.outer_d_mm:
            raise ValueError("wall_t_mm must be less than half of outer_d_mm")
        return self


class ManifoldTemplateParams(BaseModel):
    model_config = _STRICT

    outer_d_mm: OuterDiameterMm
    wall_t_mm: WallMm
    length_mm: LengthMm
    branch_count: int = Field(ge=1, le=12, strict=True)
    branch_outer_d_mm: OuterDiameterMm

    @model_validator(mode="after")
    def _branches_fit(self) -> ManifoldTemplateParams:
        if self.wall_t_mm * 2 >= self.outer_d_mm:
            raise ValueError("wall_t_mm must be less than half of outer_d_mm")
        if self.wall_t_mm * 2 >= self.branch_outer_d_mm:
            raise ValueError("wall_t_mm must be less than half of branch_outer_d_mm")
        if self.branch_outer_d_mm >= self.outer_d_mm:
            raise ValueError("branch_outer_d_mm must be less than outer_d_mm")
        if self.branch_outer_d_mm >= self.length_mm / (self.branch_count + 1):
            raise ValueError("branches do not fit: branch_outer_d_mm must be less than length_mm / (branch_count + 1)")
        return self


class TubeTemplateCreate(BaseModel):
    model_config = _STRICT

    template: Literal["tube"]
    params: TubeTemplateParams


class ManifoldTemplateCreate(BaseModel):
    model_config = _STRICT

    template: Literal["manifold"]
    params: ManifoldTemplateParams


BluecadTemplateCreate = Annotated[TubeTemplateCreate | ManifoldTemplateCreate, Field(discriminator="template")]


def template_geometry_spec(payload: TubeTemplateCreate | ManifoldTemplateCreate) -> dict[str, Any]:
    """Return the canonical GeometrySpec for one validated template request."""

    if isinstance(payload, TubeTemplateCreate):
        p = payload.params
        part = {
            "part_id": "template_tube",
            "kind": "tube_run",
            "params": {"outer_d": p.outer_d_mm, "wall_t": p.wall_t_mm, "length": p.length_mm},
        }
    else:
        m = payload.params
        part = {
            "part_id": "template_manifold",
            "kind": "manifold",
            "params": {
                "outer_d_main": m.outer_d_mm,
                "wall_t": m.wall_t_mm,
                "length": m.length_mm,
                "n_out": m.branch_count,
                "out_d": m.branch_outer_d_mm,
                "out_wall_t": m.wall_t_mm,
                # Branches are spread evenly along the header.
                "spacing": m.length_mm / (m.branch_count + 1),
            },
        }
    raw_spec = {
        "spec_version": "bluecad_geometry_spec_v0_1",
        "name": f"template_{payload.template}",
        "parts": [part],
        "connections": [],
    }
    try:
        return canonicalize_geometry_spec(raw_spec)
    except SpecValidationError as exc:
        raise TemplateError("template_geometry_invalid", "Template parameters do not form a valid GeometrySpec.", status_code=422) from exc


def _brief(payload: TubeTemplateCreate | ManifoldTemplateCreate) -> str:
    if isinstance(payload, TubeTemplateCreate):
        p = payload.params
        return f"Template tube: outer Ø {p.outer_d_mm:g} mm, wall {p.wall_t_mm:g} mm, length {p.length_mm:g} mm."
    m = payload.params
    return (
        f"Template manifold: header Ø {m.outer_d_mm:g} mm, wall {m.wall_t_mm:g} mm, length {m.length_mm:g} mm, "
        f"{m.branch_count} × Ø {m.branch_outer_d_mm:g} mm branches."
    )


def create_template_candidate(
    workspace_id: str, payload: TubeTemplateCreate | ManifoldTemplateCreate
) -> BluecadCandidateRead:
    """Create, build and validate one deterministic template candidate."""

    spec = template_geometry_spec(payload)
    candidate_id = str(uuid4())
    attempt_id = str(uuid4())
    now = utc_now()
    brief = _brief(payload)
    route_class = f"deterministic:template:{payload.template}"
    with open_sqlite_connection() as connection:
        try:
            _require_workspace(connection, workspace_id)
        except ValueError as exc:
            raise TemplateError("workspace_not_found", "Workspace not found.", status_code=404) from exc
        connection.execute(
            """
            INSERT INTO bluecad_candidates (
                id, workspace_id, brief_text, brief_digest, status, parked_reason,
                spec_artifact_id, glb_artifact_id, report_artifact_id,
                promoted_decision_id, origin, parent_candidate_id,
                loop_config_json, created_at, updated_at, notes
            ) VALUES (?, ?, ?, ?, 'generating', NULL, NULL, NULL, NULL, NULL,
                'template', NULL, '{}', ?, ?, ?)
            """,
            (
                candidate_id,
                workspace_id,
                brief,
                brief_digest(brief),
                now,
                now,
                f"template_version={TEMPLATE_VERSION}; template={payload.template}",
            ),
        )
        connection.execute(
            """
            INSERT INTO bluecad_attempts (
                id, candidate_id, attempt_no, route_class, proposal_ai_job_id,
                proposal_outcome, build_outcome, validation_verdict,
                spec_artifact_id, report_artifact_id, manifest_artifact_id,
                started_at, finished_at, error_detail_json
            ) VALUES (?, ?, 1, ?, NULL, 'not_applicable', NULL, NULL, NULL, NULL, NULL, ?, NULL, ?)
            """,
            (
                attempt_id,
                candidate_id,
                route_class,
                now,
                json.dumps({"template_version": TEMPLATE_VERSION, "params": payload.params.model_dump()}, sort_keys=True),
            ),
        )
        connection.commit()

    out_dir = candidate_work_dir(workspace_id, candidate_id, 1)
    registered: list[str] = []
    attempt_finished = False
    try:
        out_dir.mkdir(parents=True, exist_ok=False)
        spec_path = out_dir / "geometry_spec.json"
        spec_path.write_text(canonical_json(spec) + "\n", encoding="utf-8")
        result = build_geometry_spec(spec, out_dir)
        source_ref = f"bluecad_candidate:{candidate_id}:attempt:1"

        def register(path: Path, role: str) -> str:
            artifact_id = register_artifact(
                workspace_id, path, role=role, source_ref=source_ref, producer_notes=ARTIFACT_PRODUCER
            )
            registered.append(artifact_id)
            return artifact_id

        spec_artifact_id = register(spec_path, "bluecad_spec")
        report_path = result.report_path or out_dir / "validation_report.json"
        if not report_path.exists():
            raise RuntimeError("expected deterministic BLUECAD validation report is missing")
        report_artifact_id = register(report_path, "bluecad_report")
        manifest_artifact_id = None
        if result.manifest_path is not None and result.manifest_path.exists():
            manifest_artifact_id = register(result.manifest_path, "bluecad_manifest")
        glb_artifact_id = None
        glb_path = out_dir / "model.glb"
        if glb_path.exists():
            glb_artifact_id = register(glb_path, "bluecad_glb")
            registered.extend(
                register_export_artifacts(
                    workspace_id, out_dir, source_ref=source_ref, producer_notes=ARTIFACT_PRODUCER
                ).values()
            )

        verdict = "pass" if result.report.get("verdict") == "pass" else "fail"
        finish_attempt(
            attempt_id,
            proposal_outcome="not_applicable",
            build_outcome="ok" if result.verdict != "error" else _build_error_code(result.errors),
            validation_verdict=verdict,
            spec_artifact_id=spec_artifact_id,
            report_artifact_id=report_artifact_id,
            manifest_artifact_id=manifest_artifact_id,
        )
        attempt_finished = True
        update_candidate_artifacts(
            candidate_id,
            spec_artifact_id=spec_artifact_id,
            glb_artifact_id=glb_artifact_id,
            report_artifact_id=report_artifact_id,
        )
        record_validation_evidence(
            workspace_id, candidate_id, attempt_id, result.report, report_artifact_id=report_artifact_id
        )
        if verdict == "pass":
            mark_candidate_valid(candidate_id)
        else:
            park_candidate(candidate_id, "template_build_failed", notes="Deterministic template validation failed.")
    except Exception as exc:
        if not attempt_finished:
            try:
                finish_attempt(
                    attempt_id,
                    proposal_outcome="not_applicable",
                    build_outcome="template_execution_error",
                    validation_verdict="fail",
                    error_detail={"error_type": type(exc).__name__},
                )
            except Exception:
                pass
        park_candidate(candidate_id, "template_build_failed", notes=f"template_execution_error={type(exc).__name__}")
        if not registered and out_dir.exists():
            shutil.rmtree(out_dir, ignore_errors=True)
        raise TemplateError(
            "template_build_failed",
            "The deterministic template build did not complete coherently.",
            status_code=500,
        ) from exc

    candidate = get_candidate(workspace_id, candidate_id)
    if candidate is None:  # pragma: no cover - defensive persistence guard
        raise TemplateError("template_persistence_inconsistent", "Template candidate is missing.", status_code=500)
    return candidate


def _build_error_code(errors: list[dict[str, Any]]) -> str:
    if not errors:
        return "error"
    code = errors[0].get("code")
    return str(code).lower() if code else "error"
