from pathlib import Path

SERVICE = Path("backend/app/modules/ai/token_flow_evidence.py")
TEST = Path("backend/tests/test_token_flow_evidence.py")

text = SERVICE.read_text(encoding="utf-8")
old = '''            flow = _require_flow(connection, flow_id)\n            if flow["state"] != "running":\n                raise TokenFlowConflictError("only running flows can accept attempt evidence")\n\n            attempt = _require_attempt_for_evidence(connection, attempt_id)\n            if attempt["task_kind"] != flow["task_kind"]:\n                raise TokenFlowConflictError("ai_job task kind does not match flow")\n            _validate_binding(attempt, normalized)\n            _validate_usage_and_result(attempt, normalized)\n            _validate_parent_and_continuation(connection, flow, attempt_id, normalized)\n\n            if attempt["flow_id"] is not None or attempt["flow_attempt_index"] is not None:\n                _require_exact_replay(flow_id, attempt, normalized)\n                _refresh_identity(connection, flow_id)\n                connection.commit()\n                return _decode_flow(_require_flow(connection, flow_id))\n\n            _require_unwritten_evidence(attempt)\n'''
new = '''            flow = _require_flow(connection, flow_id)\n            attempt = _require_attempt_for_evidence(connection, attempt_id)\n            if attempt["task_kind"] != flow["task_kind"]:\n                raise TokenFlowConflictError("ai_job task kind does not match flow")\n            _validate_binding(attempt, normalized)\n            _validate_usage_and_result(attempt, normalized)\n            _validate_parent_and_continuation(connection, flow, attempt_id, normalized)\n\n            if attempt["flow_id"] is not None or attempt["flow_attempt_index"] is not None:\n                _require_exact_replay(flow_id, attempt, normalized)\n                _refresh_identity(connection, flow_id)\n                connection.commit()\n                return _decode_flow(_require_flow(connection, flow_id))\n\n            if flow["state"] != "running":\n                raise TokenFlowConflictError("only running flows can accept attempt evidence")\n            _require_unwritten_evidence(attempt)\n'''
if text.count(old) != 1:
    raise SystemExit("unexpected standalone evidence guard block")
SERVICE.write_text(text.replace(old, new, 1), encoding="utf-8")

tests = TEST.read_text(encoding="utf-8")
case = '''\n\ndef test_exact_replay_is_idempotent_after_flow_terminalization(\n    initialized_database,\n) -> None:\n    from app.modules.ai.token_flow_service import transition_flow_state\n\n    flow = create_flow(task_kind="synthesis")\n    _insert_job("terminal-replay")\n    evidence = _synthetic_evidence()\n    record_attempt_evidence(\n        flow_id=str(flow["id"]),\n        attempt_id="terminal-replay",\n        evidence=evidence,\n    )\n    terminal = transition_flow_state(\n        flow_id=str(flow["id"]),\n        new_state="complete",\n        terminal_reason="completed",\n        terminal_attempt_id="terminal-replay",\n    )\n\n    replay = record_attempt_evidence(\n        flow_id=str(flow["id"]),\n        attempt_id="terminal-replay",\n        evidence=evidence,\n    )\n\n    assert replay["state"] == "complete"\n    assert replay["terminal_attempt_id"] == "terminal-replay"\n    assert replay["final_accounting_digest"] == terminal["final_accounting_digest"]\n    assert replay["final_output_digest"] == terminal["final_output_digest"]\n    assert replay["ordered_attempt_ids"] == ["terminal-replay"]\n'''
if "test_exact_replay_is_idempotent_after_flow_terminalization" in tests:
    raise SystemExit("terminal replay regression test already exists")
TEST.write_text(tests + case, encoding="utf-8")
